version: '3'

services:
  php-fpm:
    build: docker/php
    container_name: php-fpm
    volumes:
      - ./website/bedrock:/var/www/html
    ports:
      - "9000:9000"
    expose:
      - 9000
    links:
      - bedrock-db
    depends_on:
      - bedrock-db

  nginx:
    build: docker/nginx
    volumes:
      - ./website/bedrock:/var/www/html/
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    links:
      - php-fpm

  bedrock-db:
    # image: bedrock-bedrock-db:latest
    image: mysql:5.7
    container_name: bedrock-db
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bedrock
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
